using System.Globalization;
using System.Text;

namespace Kbo.Gold;

/// <summary>
/// DayDigest → Obsidian-friendly Markdown. One page per day plus an index,
/// wikilinked. Renders what gold computed — zero computation (P2).
/// </summary>
internal static class DailyDigestRenderer
{
    public static string RenderIndex(IReadOnlyList<DayDigest> days)
    {
        StringBuilder markdown = new();
        _ = markdown.AppendLine("# Daily digests");
        _ = markdown.AppendLine();
        _ = markdown.AppendLine("GENERATED by `kbo report` — one page per day, newest first.");
        _ = markdown.AppendLine();
        _ = markdown.AppendLine("| Day | Sessions | KB-touch | Searches | Miss |");
        _ = markdown.AppendLine("|-----|---------:|---------:|---------:|-----:|");
        foreach (DayDigest day in days)
        {
            _ = markdown.AppendLine(CultureInfo.InvariantCulture,
                $"| [[{day.Date}]] | {day.Sessions} | {Percent(day.KbTouchRate)} | {day.Searches} | {MissRate(day)} |");
        }
        return markdown.ToString();
    }

    public static string RenderDay(DayDigest day)
    {
        StringBuilder markdown = new();
        _ = markdown.AppendLine(CultureInfo.InvariantCulture, $"# {day.Date}");
        _ = markdown.AppendLine();
        _ = markdown.AppendLine("[[index|← all days]] · GENERATED by `kbo report`");
        _ = markdown.AppendLine();

        _ = markdown.AppendLine("## Sessions");
        _ = markdown.AppendLine();
        _ = markdown.AppendLine(CultureInfo.InvariantCulture,
            $"**{day.Sessions}** session(s) active — **{Percent(day.KbTouchRate)}** touched the knowledge base ({day.SessionsTouchingKb} of {day.Sessions}).");
        _ = markdown.AppendLine();
        AppendCounts(markdown, "By agent", day.ByAgent);
        AppendCounts(markdown, "By repository", day.ByRepo);
        AppendSessionTable(markdown, day.SessionDetail);

        _ = markdown.AppendLine("## Skills used");
        _ = markdown.AppendLine();
        if (day.SkillsUsed.Count is 0)
        {
            _ = markdown.AppendLine("_No skills invoked._");
            _ = markdown.AppendLine();
        }
        else
        {
            foreach (DayCount skill in day.SkillsUsed)
            {
                _ = markdown.AppendLine(CultureInfo.InvariantCulture, $"- {Cell(skill.Label)} — {skill.Count}");
            }
            _ = markdown.AppendLine();
        }

        _ = markdown.AppendLine("## Knowledge searches");
        _ = markdown.AppendLine();
        _ = markdown.AppendLine(CultureInfo.InvariantCulture,
            $"**{day.Searches}** search(es) — **{day.SearchHits}** hit, **{day.SearchZeroHits}** found nothing ({MissRate(day)} miss).");
        _ = markdown.AppendLine();
        if (day.TopZeroHitQueries.Count > 0)
        {
            _ = markdown.AppendLine("Top zero-hit queries (candidates for new or better-named notes):");
            _ = markdown.AppendLine();
            foreach (DayCount query in day.TopZeroHitQueries)
            {
                _ = markdown.AppendLine(CultureInfo.InvariantCulture, $"- `{Inline(query.Label)}` ×{query.Count}");
            }
            _ = markdown.AppendLine();
        }

        _ = markdown.AppendLine("## Knowledge reads");
        _ = markdown.AppendLine();
        _ = markdown.AppendLine(CultureInfo.InvariantCulture, $"**{day.TotalReads}** read(s) of registered knowledge.");
        _ = markdown.AppendLine();
        AppendCounts(markdown, "By layer", day.ReadsByLayer);

        _ = markdown.AppendLine("## Tokens");
        _ = markdown.AppendLine();
        _ = markdown.AppendLine(CultureInfo.InvariantCulture,
            $"Fresh input: **{day.InputTokens:N0}** · cache-read: **{day.CacheReadTokens:N0}**.");
        return markdown.ToString();
    }

    private static void AppendSessionTable(StringBuilder markdown, IReadOnlyList<DaySession> sessions)
    {
        if (sessions.Count is 0)
        {
            return;
        }
        _ = markdown.AppendLine("_Per session_ (reads · searches · skills · writes):");
        _ = markdown.AppendLine();
        _ = markdown.AppendLine("| Time | Agent | Repo | R | S | Sk | W | KB | Tokens in/cache |");
        _ = markdown.AppendLine("|------|-------|------|--:|--:|---:|--:|:--:|-----------------|");
        foreach (DaySession session in sessions)
        {
            string touch = session.TouchedKb ? "✓" : "—";
            string tokens = string.Create(CultureInfo.InvariantCulture, $"{session.InputTokens / 1000}k/{session.CacheReadTokens / 1000}k");
            _ = markdown.AppendLine(CultureInfo.InvariantCulture,
                $"| {session.Time} | {Cell(session.Agent)} | {Cell(RepoLabel(session.Repo))} | {session.Reads} | {session.Searches} | {session.Skills} | {session.Writes} | {touch} | {tokens} |");
        }
        _ = markdown.AppendLine();
    }

    private static string RepoLabel(string repo)
    {
        string trimmed = repo.TrimEnd('/');
        int slash = trimmed.LastIndexOf('/');
        return slash >= 0 && slash < trimmed.Length - 1 ? trimmed[(slash + 1)..] : trimmed;
    }

    private static void AppendCounts(StringBuilder markdown, string heading, IReadOnlyList<DayCount> counts)
    {
        _ = markdown.AppendLine(CultureInfo.InvariantCulture, $"_{heading}_:");
        if (counts.Count is 0)
        {
            _ = markdown.AppendLine();
            _ = markdown.AppendLine("- (none)");
            _ = markdown.AppendLine();
            return;
        }
        foreach (DayCount count in counts)
        {
            _ = markdown.AppendLine(CultureInfo.InvariantCulture, $"- {Cell(count.Label)} — {count.Count}");
        }
        _ = markdown.AppendLine();
    }

    private static string Percent(double rate) => (rate * 100).ToString("0", CultureInfo.InvariantCulture) + "%";

    private static string MissRate(DayDigest day)
    {
        double rate = day.Searches == 0 ? 0 : (double)day.SearchZeroHits / day.Searches;
        return Percent(rate);
    }

    private static string Cell(string value) => value.Replace("|", "\\|", StringComparison.Ordinal);

    private static string Inline(string value) => value.Replace("|", "\\|", StringComparison.Ordinal).Replace('`', '\'');
}
